### ISSUE TITLE
We should just use precommit

### ISSUE THREAD

**Issue by wisnuprama** [cymonevo-luna/proyekin-backend#4]
I see that so many commenting about some pep8. To improve our productivity, we should use pre-commit hook. 

Consider sorting the import statements using `isort`

_Originally posted by @hashlash in https://github.com/cymonevo-luna/proyekin-backend/pull/2_

**Comment by hashlash** [comment]
Wanna use this package https://pre-commit.com/?

**Comment by hashlash** [comment]
Implemented on https://github.com/cymonevo-luna/proyekin-backend/pull/2/commits/fe05d89e27b589cde52ab326460c35e3423c4805
